version: "3.3"
services:
  application:
    image: primeqa/ui:0.0.1
    container_name: primeqa-ui
    ports:
      - 82:82
    environment:
      - API_URL=http://${PUBLIC_IP:-0.0.0.0}:50059
    depends_on:
      - orchestrator
  orchestrator:
    image: primeqa/orchestrator:0.0.1
    container_name: primeqa-orchestrator
    ports:
      - 50059:50059
    environment:
      - STORE_DIR=/store
      - num_rest_server_workers=1
      - require_ssl=false
    volumes:
      - ./orchestrator-store:/store:rw
    depends_on:
      - primeqa
  primeqa:
    image: primeqa/services:0.9.3-cpu
    container_name: primeqa-services
    ports:
      - 50051:50051
    runtime: nvidia
    environment:
      - STORE_DIR=/store
      - num_grpc_server_workers=1
      - require_ssl=false
    volumes:
      - ./cache/huggingface:/cache/huggingface:rw
      - ./primeqa-store:/store:rw
